wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.8.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.6
    start_time: 1628684567
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 2
      4: 3.7.6
      5: 0.12.0
      6: 4.8.2
      8:
      - 1
      - 2
      - 5
